insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'25 minutes','shakshuka','Shakshuka','https://www.youtube.com/watch?v=IGx6etMEKr0&feature=youtu.be','One of the most well known Middle Eastern breakfasts, get ready for a taste sensation with Shakshuka','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','harissasoyeeggs','Harissa Soy Eggs','https://www.youtube.com/watch?v=tLqkOgW4Dbc&feature=youtu.be','Harissa is north african‘s answer to gochujang and its delicious','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','greenshakshuka','Green Shakshuka','https://www.youtube.com/watch?v=qLy0AqiKIOA&feature=youtu.be','The green version of the famous Middle Eastern breakfast Shakshuka','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','huevosrancheros','Huevos Rancheros','https://www.youtube.com/watch?v=NwJKFeSydwE&feature=youtu.be','A classic mexican breakfast that is packed with flavor','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','savoryfrenchtoast','Savory French Toast','https://www.youtube.com/watch?v=zZBAdROVCXw&feature=youtu.be','Everyone knows what French Toast is, but did you ever try to make it savory and filled with cheese? Well, say hello to this unique breakfast dish','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','koreanshakshuka','Korean Shakshuka','https://www.youtube.com/watch?v=iuUwf9SKrbA&feature=youtu.be',' This is the Korean way to make eggs. Spicy and delicious','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','tunasandwich','Tuna Sandwich','https://www.youtube.com/watch?v=zZBAdROVCXw&feature=youtu.be','My personal double double that is packed with protein','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','capreseomelette','Caprese Omelette','https://www.youtube.com/watch?v=YNJ3U7AqyKU&feature=youtu.be','The italian way to make a high protein omelette omelette','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','breakfastburrito','Breakfast Burrito','https://www.youtube.com/watch?v=PY7qk6BtkkQ&feature=youtu.be','Burritos for breakfast will keep you full and happy until lunch','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','frenchtoast','French Toast','https://www.youtube.com/watch?v=zZBAdROVCXw&feature=youtu.be','One of the most iconic high protein breakfast in the fitness world','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'20 minutes','italianeggwhitebites','Italian egg white  bites','','Small egg bites are the perfect snack during the day or they can be used as an easy breakfast when made in a big batch','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'20 minutes','italianeggbites','Italian egg bites','','Italian style egg bites but this time with whole eggs. Perfect for breakfast where you need more calories to get you through the day','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','spicyfritata','Spicy Fritata','https://www.youtube.com/watch?v=QIgHTm5bHlc&feature=youtu.be','For those days when you just fancy a bit of spice in your morning breakfast','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'10 minutes','pbsweetcrepe','Sweet crepe','https://www.youtube.com/watch?v=nqnauYoBRBQ&feature=youtu.be','Crepes are the french way to make pancakes. But this is my way to make them healthier','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'5 minutes','yogurtpowerbowl','Yogurt Power Bowl','https://www.youtube.com/watch?v=nqnauYoBRBQ&feature=youtu.be','For days where you just want protein in a simple way. Here’s my simple and sweet yogurt power bow','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'5 minutes','bananatortilla','PB & Banana Tortilla','https://www.youtube.com/watch?v=nqnauYoBRBQ&feature=youtu.be',' Ever tried sweet tortillas for breakfast? These taste amazing and so easy to prepare in the morning','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','menemen','MENEMEN','https://www.youtube.com/watch?v=zZBAdROVCXw&feature=youtu.be','This classic turkish breakfast is something I love making on those colder days when you need something warm and delicious','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'30 minutes','savorybakedoats','Savory Baked Oats','','Not enough people give savory oats a try. They are amazing in combination with spices','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'20 minutes','potatohash','Potato Hash','https://www.youtube.com/watch?v=dLairfd8bZU&feature=youtu.be','Potatoes, eggs and ham. What more do you need for a hearty breakfast?','felu');
insert into meal (id,category_id,estimatedtime,image,"name",video,small_description,tag) values (nextval('mealsequence'),1,'15 minutes','savoryfilledcrepe','Savory Filled Crepe','','A French crepe but savory and filled with cheese','felu');



