-- Dairy products
insert into ingredient (id,name) values (nextval('ingredientsequence'),'leite 1%');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'leite de manteiga 1%');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'yogurt greego 0.2%');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'queijo creme 0.2%');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'queijo americano');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'queijo cottage 1%');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'iogurt skyr natural');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'leite evaporado');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'queijo feta');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'mozzarella light');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'queijo da vaca que ri');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'queijo ralado mozarella');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pó de proteina whey');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pó de caseina');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'leite magro');
-- baking / breakfast
insert into ingredient (id,name) values (nextval('ingredientsequence'),'fermento em po');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'bicarbonato de sodio');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'stevia');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'adoçante');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'clara de ovo');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'ovo');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pó de cacau');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'aveia');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'farinha');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'amendoin em po');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'manteiga de amendoin');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pao');
-- Sides
insert into ingredient (id,name) values (nextval('ingredientsequence'),'shirataki noodles');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'batatas');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'batatas doce');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'udon noodles');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'arroz instantaneo')
insert into ingredient (id,name) values (nextval('ingredientsequence'),'fatia de pão');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'tortilha de trigo');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'arroz');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'massa');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'jalapeno');
-- Meat
insert into ingredient (id,name) values (nextval('ingredientsequence'),'peito de frango');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'peito de peru');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'atum em lata');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'lombo de galinha fatiado');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'lombo de porco fatiado');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'lombo de vaca');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'carne picada 5% gorda');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'lombo de porco');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'coxa de frango');
-- Vegetables
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pak choi');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'aipo');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'couve');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'courgette');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'tomate');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pimento');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'asparagus');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'cogumelos');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'couve cali');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'beringela');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'nabo');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'funcho');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'broculos');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'cebolas');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'cenouras');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'couves bruxelas');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'alho');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'ervilha');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'espargos');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'salsa');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'azeitona');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'manjericao');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'espinafre');
-- Fruits
insert into ingredient (id,name) values (nextval('ingredientsequence'),'melancia');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'morango');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pessego');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'meloa');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'amora');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'papaya');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'laranja');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'cereja');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pessego');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'nectarina');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'maça');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'framboesa');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'mirtilho');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'manga');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'kiwi');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'banana');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'abacate');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'limao');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'nozes');
-- Condiments
insert into ingredient (id,name) values (nextval('ingredientsequence'),'vinagre de arroz');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'lata de tomate em pedaços');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'ketchup');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'mostarda');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'molho de tomate');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'leite de coco');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'molho de soja');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'molho picante');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'gochujang');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'mel');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'gelatina em pó');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'azeite');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'amido de milho');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'caldo de knorr vegetais');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'po de cebola');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'po de alho');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'sal');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'oregaos');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'paprika');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pimenta cayene');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pimenta preta');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'cuminhos');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pimentao doce');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'piri-piri');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'curcuma');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'harissa paste');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'canela');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'agua');
insert into ingredient (id,name) values (nextval('ingredientsequence'),'pure de tomate');
